[project]
name = "GeoPakTile"
version = "2.0.1"
description = "Create a Geopackage XYZ Tile layer."
readme = "README.md"
authors = [
    { name = "apwebber", email = "39490780+apwebber@users.noreply.github.com" }
]
license = "MIT"
license-files = ["LICENSE.md"]
keywords = ["GIS", "Geopackage", "Tiles", "XYZ", "gpkg"]
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 4 - Beta",

    # Specify the Python versions you support here.
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "typing_extensions>=4.0; python_version < '3.11'",
    "morecantile>=6.2.0",
    "numpy>=2.2.6",
    "requests>=2.34.2",
    "pillow>=12.3.0",
]

[project.urls]
Homepage = "https://github.com/apwebber/GeoPakTile"
Documentation = "https://github.com/apwebber/GeoPakTile"
Repository = "https://github.com/apwebber/GeoPakTile.git"   
Issues = "https://github.com/apwebber/GeoPakTile/issues"

[project.scripts]
geopaktile = "geopaktile:main"

[build-system]
requires = ["uv_build>=0.11.2,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest",
    "diskcache",
    "rasterio"
]
